# Generated by Django 6.1.1 on 2026-09-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='user_id',
            field=models.CharField(blank=True, help_text='Supabase User ID', max_length=255, null=True),
        ),
    ]
