# Generated by Django 6.1.1 on 2026-09-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_site_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='bot_name',
            field=models.CharField(default='AI Assistant', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='theme_color',
            field=models.CharField(default='#000000', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
