# Generated by Django 6.1.1 on 2026-09-08 11:12

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_site_bot_name_site_theme_color_site_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='widget_token',
            field=models.CharField(default=chatbot.models.generate_widget_token, help_text='Secret 6-character token for the widget', max_length=10),
        ),
    ]
